---
- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: install packages
    package: 
      name:
        - htop
        - tmux
        - neovim
        - zsh

  - name: copy .zshrc file
    copy:
      src: dotfiles/zshrc
      dest: /home/mentat/.zshrc
      owner: mentat
      group: mentat
